[project]
name = "python-ai-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.128.0",
    "google-genai>=1.56.0",
    "greenlet>=3.3.0",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
